---

- hosts: all
  become: true
  tasks:

  - name: INSTALL APACHE and LIBAPACHE2-MOD-HPH
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
